version: '3.8'

services:
  airflow:
    build: ./scraper
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__WEBSERVER__AUTH_BACKEND=airflow.auth.backend.basic_auth

      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+pymysql://root:${DB_PASSWORD}@mysql:3306/reddit_posts
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql+pymysql://root:${DB_PASSWORD}@mysql:3306/reddit_posts
      - AIRFLOW__CELERY__RESULT_BACKEND=db+mysql+pymysql://root:${DB_PASSWORD}@mysql:3306/reddit_posts

      # Reddit API credentials
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_SECRET=${REDDIT_SECRET}
      - REDDIT_APP_NAME=newsbot_airflow
      - REDDIT_USERNAME=${REDDIT_USERNAME}
      - REDDIT_PASSWORD=${REDDIT_PASSWORD}

    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: reddit_posts
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD}

  newsbot:
    build: ./newsbot
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=reddit_posts
      - GEM_API=${GEM_API}
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:

